#!/usr/bin/perl -w

use esmith::Build::CreateLinks qw(:all);

#--------------------------------------------------
## functions for manager panel
##--------------------------------------------------

my $event = 'nethserver-nfs-update';
event_actions ( $event, 'initialize-default-databases' => '00');

foreach (qw(sysconfig/nfs exports ))
{
    templates2events("/etc/$_", qw(
    nethserver-nfs-update
    ));
}

#Template to expand
foreach (qw(exports))
{
    templates2events("/etc/$_", qw(
    interface-update
    ibay-create
    ibay-delete
    ibay-modify
    ));
}

foreach $event (qw(nethserver-nfs-update))
{
    event_services($event,
        'nfs-lock' => 'restart', 
        'nfs' => 'restart',
        'rpcbind' => 'restart' );
}


for my $event (qw(nethserver-nfs-update interface-update ibay-create ibay-delete ibay-modify))
{
    event_actions ($event, 'nethserver-nfs-exportfs' => '95');
}


#The service rpcbind needs to be restarted before nfs service, 
#but sometime it start before so I had to do a specific action
#for my $event (qw(nethserver-nfs-update interface-update ibay-create ibay-delete ibay-modify))
#{
#    event_actions ($event, 'nethserver-nfs-restart-rpcbind' => '05');
#}
