#!/usr/bin/perl -w

use esmith::Build::CreateLinks qw(:all);

#--------------------------------------------------
## functions for manager panel
##--------------------------------------------------

event_actions (nethserver-nfs-update, 'initialize-default-databases' => '00');

foreach (qw(sysconfig/nfs exports ))
{
    templates2events("/etc/$_", qw(
    nethserver-nfs-update
    ));
}
#add this event for change /etc/exports with new local network
foreach (qw(exports))
{
    templates2events("/etc/$_", qw(
    interface-update
    ibay-create
    ibay-delete
    ibay-modify
    ));
}

foreach $event (qw(nethserver-nfs-update interface-update ibay-create ibay-delete ibay-modify))
{
    event_services($event,
        'nfs-lock' => 'restart', 
        'nfs' => 'restart' );
}

#The service rpcbind needs to be restarted before nfs service, 
#but sometime it start before so I had to do a specific action
for my $event (qw(nethserver-nfs-update interface-update ibay-create ibay-delete ibay-modify))
{
    event_actions ($event, 'nethserver-nfs-restart-rpcbind' => '05');
}
